### ISSUE TITLE
locations map sometimes doesn't work on reload

### ISSUE THREAD

**Issue by linberg** [linberg/ediblehood#2]

**Comment by linberg** [comment]
http://stackoverflow.com/questions/17317816/rails-javascript-only-works-after-reload

**Comment by kajatiger** [comment]
did you try to refresh in another browser?

**Comment by linberg** [comment]
i'm trying to make it work so that it doesn't need the refresh, will add this to `application.js`

```
//= require jquery
    //= require turbolinks
    //= require jquery_ujs

```
